### ISSUE TITLE
Changing track position

### ISSUE THREAD

**Issue by mariusor** [mariusor/mpris-ctl#25]
Add support for changing track position.

I'm thinking using an argument like `--skip +10s`, `--skip -1m`.

_Based on the comment by @JosefLitos in https://github.com/mariusor/mpris-ctl/issues/23#issuecomment-1685325655_

**Comment by mariusor** [comment]
I added some support for `seek [-]Xs` in the master branch, if anyone is willing to test it.

**Comment by litoj** [comment]
The position changing works great. I tried switching back to `mpris-ctl` but didn't manage to make `info` command work with any argument - always exits with `1`, no message. (I noticed this is caused by me using `CC='gcc -O3'`, `-O2` works. Can this be fixed?)

Also when I try `mpris-ctl --player active --player inactive pp`, both separately and together can pause the client, but no way to play it again - probably issue of replacing `active` before `inactive`.

**Comment by mariusor** [comment]
> using `CC='gcc -O3'`, `-O2` works. 

That's an interesting bug, I'll have a look.

I realized that the changes made to have `seek` working with negative times break some of the existing command line argument parsing, so it might be some time until I manage to fix all warts.

I'll probably do a new release at that time. :)

**Comment by mariusor** [comment]
I added the `seek` command in version [v0.9](https://github.com/mariusor/mpris-ctl/releases/tag/v0.9).

@JosefLitos please check if the `info` command works better now, I have changed how we load active/inactive/named players so it might be slightly better.
